import {v4 as uuidv4} from "uuid";

function util(){
    return[
        {
            name: "Porkanda Singam (EDM Version)",
            artist: "Anirudh Ravichander",
            cover: "https://a10.gaanacdn.com/gn_img/albums/01A3mar3NQ/A3maLLY93N/size_l.jpg",
            id: uuidv4(),
            active: true,
            color: ["#4A2820", "#FB8830"],
            audio: "https://saavn.xyz/tamil/Vikram/Porkanda%20Singam%20(EDM%20Version).mp3",
        },
        {
            name: "Rolex Theme",
            artist: "Anirudh Ravichander",
            cover: "https://upload.wikimedia.org/wikipedia/en/5/59/Vikram_soundtrack.jpg",
            id: uuidv4(),
            active: false,
            color: ["#2F2F2F", "#A3A3A3"],
            audio: "https://nzt6ku-a.akamaihd.net/downloads/ringtones/files/mp3/audiocutter-yt1s-com-rolex-climax-3-57436.mp3",
        },
        {
            name: "Megham Karukatha",
            artist: "Anirudh Ravichander",
            cover: "https://c.saavncdn.com/383/Megham-Karukatha-From-Thiruchitrambalam-Tamil-2022-20220715184158-500x500.jpg",
            id: uuidv4(),
            active: false,
            color: ["#7B51A0", "#F1F1F1"],
            audio: "https://saavn.xyz/tamil/Thiruchitrambalam/Megham%20Karukatha.mp3",
        },
        {
            name: "Soul of Doctor (Theme)",
            artist: "Anirudh Ravichander",
            cover: "https://c.saavncdn.com/312/Doctor-Tamil-2021-20211005133149-500x500.jpg",
            id: uuidv4(),
            active: false,
            color: ["#020202", "#A8BDAE"],
            audio: "https://saavn.xyz/tamil/Doctor/Soul of Doctor (Theme).mp3",
        },
        {
            name: "Polakattum Para Para",
            artist: "Anirudh Ravichander",
            cover: "https://c.saavncdn.com/347/Master-Tamil-2020-20200316084627-500x500.jpg",
            id: uuidv4(),
            active: false,
            color: ["#210D0F", "#D29D73"],
            audio: "https://saavn.xyz/tamil/Master/Polakatum Para Para.mp3",
        },
        {
            name: "Yakkai Thiri",
            artist: "A.R.Rahman",
            cover: "https://c.saavncdn.com/929/Aayitha-Ezhutu-Tamil-2004-20190629140126-500x500.jpg",
            id: uuidv4(),
            active: false,
            color: ["#D4482A", "#D38B3D"],
            audio: "https://saavn.xyz/tamil/Aaytha Ezhuthu/Yakkai Thiri.mp3",
        },
        {
            name: "Kikku Yerudhey",
            artist: "A.R.Rahman",
            cover: "https://c.saavncdn.com/136/Padayppa-1999-500x500.jpg",
            id: uuidv4(),
            active: false,
            color: ["#21242A", "#CACDDE"],
            audio: "https://saavn.xyz/tamil/Padayappa/Kikku Yerudhey.mp3",
        },
        // {
        //     name: "",
        //     artist: "",
        //     cover: "",
        //     id: uuidv4(),
        //     active: false,
        //     color: [],
        //     audio: "",
        // },
        // {
        //     name: "",
        //     artist: "",
        //     cover: "",
        //     id: uuidv4(),
        //     active: false,
        //     color: [],
        //     audio: "",
        // },
        // {
        //     name: "",
        //     artist: "",
        //     cover: "",
        //     id: uuidv4(),
        //     active: false,
        //     color: [],
        //     audio: "",
        // },
        // {
        //     name: "",
        //     artist: "",
        //     cover: "",
        //     id: uuidv4(),
        //     active: false,
        //     color: [],
        //     audio: "",
        // },
    ];
}

export default util;